title: Donghoon Shin
author:
  name: Donghoon Shin
  email: dhoon@uw.edu
description: >
  HCI researcher | Ph.D. student at the Unviersity of Washington
google_analytics_id: UA-215543768-1

show_excerpts: false # set to true to show excerpts on the homepage
permalink: /:title

url: "https://donghoon.io" # the base hostname & protocol for your site

plugins:
 - jekyll-feed
 - jekyll-seo-tag
 - jekyll-sitemap

collections:
  publication:
    output: true

theme: minima