title: Noah Yi-Ting Hung
author:
  name: Noah Yi-Ting Hung
  email: yhung7@gsu.edu
description: >
  PhD student in machine learning and statistics focused on interpretable modeling, uncertainty, and scientific computing
google_analytics_id: UA-215543768-1

show_excerpts: false # set to true to show excerpts on the homepage
permalink: /:title

url: "https://ythung85.github.io" # the base hostname & protocol for your site

plugins:
 - jekyll-feed
 - jekyll-seo-tag
 - jekyll-sitemap

collections:
  publication:
    output: true

theme: minima
